#ifndef PROSARY_UI_STRINGS_H
#define PROSARY_UI_STRINGS_H

/* Existing settings/mystery labels follow the native Windows resource tables.
 * The remaining translations describe only terminal controls, never prayer text.
 * Columns: English, Hebrew, Arabic, Russian, Filipino, French, Italian, Ukrainian. */
enum UiText {
    U_PRAYERS, U_SETTINGS, U_HELP, U_INTERFACE, U_LANGUAGE, U_MYSTERIES,
    U_FORM, U_DAY, U_STEP, U_COMPLETE, U_FOOT_PRAYER, U_FOOT_LIBRARY,
    U_FOOT_SETTINGS, U_FOOT_HELP, U_SCROLL, U_SELECT_HINT, U_HELP_BODY,
    U_RTL_LIMIT, U_FALLBACK, U_SAVE_ERROR, U_LOAD_ERROR, U_EMPTY,
    U_SMALL, U_JOYFUL, U_SORROWFUL, U_GLORIOUS, U_LUMINOUS,
    U_COMPLETE_HINT, U_SETTINGS_HINT, U_READY, U_NO_TEXT, U_MIXED, U_FALLBACK_TEXT,
    U_KEYBOARD_ARROWS, U_KEYBOARD_SPACE, U_ON, U_OFF
};
static const char *const ui_codes[] = { "en", "he", "ar", "ru", "tl", "fr", "it", "uk" };
static const char *const ui_names[] = {
    "English", "עברית", "العربية", "Русский", "Filipino", "Français", "Italiano", "Українська"
};
static const char *const ui_text[][8] = {
    {"Prayers", "תפילות", "الصلوات", "Молитвы", "Mga Panalangin", "Prières", "Preghiere", "Молитви"},
    {"Settings", "הגדרות", "الإعدادات", "Настройки", "Mga Setting", "Réglages", "Impostazioni", "Налаштування"},
    {"Help", "עזרה", "المساعدة", "Справка", "Tulong", "Aide", "Aiuto", "Довідка"},
    {"App Language", "שפת היישומון", "لغة التطبيق", "Язык приложения", "Wika ng App", "Langue de l’app", "Lingua dell’app", "Мова застосунку"},
    {"Prayer Language", "שפת התפילה", "لغة الصلاة", "Язык молитвы", "Wika ng Panalangin", "Langue de prière", "Lingua di preghiera", "Мова молитви"},
    {"Mysteries", "רזים", "الأسرار", "Тайны", "Mga Misteryo", "Mystères", "Misteri", "Таємниці"},
    {"Form", "נוסח", "الصيغة", "Вариант", "Anyo", "Forme", "Forma", "Варіант"},
    {"Day", "יום", "اليوم", "День", "Araw", "Jour", "Giorno", "День"},
    {"Step", "שלב", "الخطوة", "Шаг", "Hakbang", "Étape", "Passo", "Крок"},
    {"Prayer complete", "התפילה הסתיימה", "اكتملت الصلاة", "Молитва завершена", "Tapos na ang panalangin", "Prière terminée", "Preghiera completata", "Молитву завершено"},
    {"Left/Right: prayer  Up/Down: scroll  Tab: focus  F1: help  q: quit", "שמאל/ימין: תפילה  מעלה/מטה: גלילה  Tab: מיקוד  F1: עזרה  q: יציאה", "يسار/يمين: الصلاة  أعلى/أسفل: تمرير  Tab: التركيز  F1: مساعدة  q: خروج", "Влево/вправо: молитва  Вверх/вниз: прокрутка  Tab: фокус  F1: справка  q: выход", "Kaliwa/Kanan: panalangin  Taas/Baba: scroll  Tab: pokus  F1: tulong  q: labas", "Gauche/Droite : prière  Haut/Bas : défiler  Tab : zone  F1 : aide  q : quitter", "Sinistra/Destra: preghiera  Su/Giù: scorri  Tab: area  F1: aiuto  q: esci", "Ліворуч/праворуч: молитва  Вгору/вниз: прокрутка  Tab: фокус  F1: довідка  q: вихід"},
    {"Up/Down: choose  Enter: open  Tab: reader  F1: help  q: quit", "מעלה/מטה: בחירה  Enter: פתיחה  Tab: קריאה  F1: עזרה  q: יציאה", "أعلى/أسفل: اختيار  Enter: فتح  Tab: القراءة  F1: مساعدة  q: خروج", "Вверх/вниз: выбор  Enter: открыть  Tab: чтение  F1: справка  q: выход", "Taas/Baba: pumili  Enter: buksan  Tab: basa  F1: tulong  q: labas", "Haut/Bas : choisir  Entrée : ouvrir  Tab : lecture  F1 : aide  q : quitter", "Su/Giù: scegli  Invio: apri  Tab: lettura  F1: aiuto  q: esci", "Вгору/вниз: вибір  Enter: відкрити  Tab: читання  F1: довідка  q: вихід"},
    {"Up/Down: choose  Left/Right: change  Esc: prayers  q: quit", "מעלה/מטה: בחירה  שמאל/ימין: שינוי  Esc: תפילות  q: יציאה", "أعلى/أسفل: اختيار  يسار/يمين: تغيير  Esc: الصلوات  q: خروج", "Вверх/вниз: выбор  Влево/вправо: изменить  Esc: молитвы  q: выход", "Taas/Baba: pumili  Kaliwa/Kanan: baguhin  Esc: panalangin  q: labas", "Haut/Bas : choisir  Gauche/Droite : modifier  Échap : prières  q : quitter", "Su/Giù: scegli  Sinistra/Destra: modifica  Esc: preghiere  q: esci", "Вгору/вниз: вибір  Ліворуч/праворуч: змінити  Esc: молитви  q: вихід"},
    {"Up/Down: scroll  Esc: return  Tab: library  q: quit", "מעלה/מטה: גלילה  Esc: חזרה  Tab: ספרייה  q: יציאה", "أعلى/أسفل: تمرير  Esc: رجوع  Tab: المكتبة  q: خروج", "Вверх/вниз: прокрутка  Esc: назад  Tab: библиотека  q: выход", "Taas/Baba: scroll  Esc: bumalik  Tab: aklatan  q: labas", "Haut/Bas : défiler  Échap : retour  Tab : bibliothèque  q : quitter", "Su/Giù: scorri  Esc: torna  Tab: raccolta  q: esci", "Вгору/вниз: прокрутка  Esc: назад  Tab: бібліотека  q: вихід"},
    {"Lines", "שורות", "السطور", "Строки", "Mga linya", "Lignes", "Righe", "Рядки"},
    {"Choose a prayer and press Enter.", "בחרו תפילה והקישו Enter.", "اختر صلاة واضغط Enter.", "Выберите молитву и нажмите Enter.", "Pumili ng panalangin at pindutin ang Enter.", "Choisissez une prière et appuyez sur Entrée.", "Scegli una preghiera e premi Invio.", "Виберіть молитву й натисніть Enter."},
    {
      "Use Tab to move between the library and the reading pane. Space or Enter advances; Backspace goes back. Settings can turn arrow navigation and Space advance off independently.\n\nIn the library, Up/Down chooses an item; Enter opens it.\n\nWhile reading, Left/Right moves to the previous/next prayer. Up/Down scrolls the text. Page Up/Page Down scrolls a page. Home/End moves to the top/bottom of the text.\n\nAt the final prayer, Enter marks the session complete. Backspace returns to the prayer.\n\nOpen Settings to change the app language, prayer language, mysteries, form, or day. Left/Right changes the selected value. Changing a prayer setting restarts the prayer.\n\nEsc returns to the library. F1 or ? opens this help. q saves progress and quits. Progress is saved after every change.\n\nOn narrow terminals, Tab switches between the library and reader. Resize at any time; your place is preserved.",
      "Tab מעביר בין הספרייה לאזור הקריאה. רווח או Enter מתקדמים; Backspace חוזר. ניתן לכבות בנפרד ניווט בחצים והתקדמות ברווח בהגדרות. בממשק עברי או ערבי כיוון החצים הפוך.\n\nבספרייה, מעלה/מטה בוחר פריט; Enter פותח אותו.\n\nבקריאה, ימין/שמאל עובר לתפילה הקודמת/הבאה. מעלה/מטה גולל את הטקסט. Page Up/Page Down גולל עמוד. Home/End עובר לתחילת/סוף הטקסט.\n\nבתפילה האחרונה, Enter מסמן את סיום התפילה. Backspace חוזר לתפילה.\n\nבהגדרות ניתן לשנות את שפת היישומון, שפת התפילה, הרזים, הנוסח או היום. שמאל/ימין משנה את הערך. שינוי הגדרת תפילה מתחיל אותה מחדש.\n\nEsc חוזר לספרייה. F1 או ? פותח עזרה. q שומר את ההתקדמות ויוצא. ההתקדמות נשמרת לאחר כל שינוי.\n\nבמסוף צר, Tab מחליף בין הספרייה לקריאה. שינוי גודל שומר על מיקומכם.",
      "ينقل Tab التركيز بين المكتبة ومنطقة القراءة. المسافة أو Enter للتقدم وBackspace للرجوع. يمكن تعطيل التنقل بالأسهم والتقدم بالمسافة كلٌّ على حدة في الإعدادات. ينعكس اتجاه الأسهم في الواجهة العربية والعبرية.\n\nفي المكتبة، أعلى/أسفل لاختيار عنصر؛ وEnter لفتحه.\n\nأثناء القراءة، يمين/يسار للصلاة السابقة/التالية. أعلى/أسفل لتمرير النص. Page Up/Page Down لتمرير صفحة. Home/End لبداية/نهاية النص.\n\nفي الصلاة الأخيرة، Enter لتحديد اكتمال الجلسة. Backspace للعودة إلى الصلاة.\n\nافتح الإعدادات لتغيير لغة التطبيق أو الصلاة أو الأسرار أو الصيغة أو اليوم. يسار/يمين يغيّر القيمة. تغيير إعداد الصلاة يعيدها من البداية.\n\nEsc يعود إلى المكتبة. F1 أو ? يفتح المساعدة. q يحفظ التقدم ويخرج. يُحفظ التقدم بعد كل تغيير.\n\nفي الطرفيات الضيقة، Tab يبدّل بين المكتبة والقراءة. تغيير الحجم يحفظ موضعك.",
      "Tab переключает фокус между библиотекой и областью чтения. Пробел или Enter — вперёд, Backspace — назад. Стрелки и пробел можно отключить отдельно в настройках.\n\nВ библиотеке Вверх/вниз выбирает пункт; Enter открывает его.\n\nПри чтении Влево/вправо переходит к предыдущей/следующей молитве. Вверх/вниз прокручивает текст. Page Up/Page Down прокручивает страницу. Home/End переходит к началу/концу текста.\n\nНа последней молитве Enter отмечает завершение. Backspace возвращает к молитве.\n\nВ настройках можно изменить язык приложения, язык молитвы, тайны, вариант или день. Влево/вправо меняет значение. Изменение настройки молитвы начинает её заново.\n\nEsc возвращает в библиотеку. F1 или ? открывает справку. q сохраняет прогресс и выходит. Прогресс сохраняется после каждого изменения.\n\nВ узком окне Tab переключает библиотеку и чтение. Изменение размера сохраняет ваше место.",
      "Gamitin ang Tab upang lumipat sa aklatan at bahaging pambasa. Space o Enter para magpatuloy; Backspace para bumalik. Maaaring i-off nang magkahiwalay ang mga arrow at Space sa Mga Setting.\n\nSa aklatan, Taas/Baba ang pagpili; Enter ang pagbukas.\n\nHabang nagbabasa, Kaliwa/Kanan ang nakaraan/susunod na panalangin. Taas/Baba ang pag-scroll. Page Up/Page Down ang isang pahina. Home/End ang simula/dulo ng teksto.\n\nSa huling panalangin, Enter ang pagtatapos. Backspace ang pagbabalik sa panalangin.\n\nSa Mga Setting, baguhin ang wika ng app, wika ng panalangin, mga misteryo, anyo, o araw. Kaliwa/Kanan ang pagbabago. Ang pagbabago ng setting ng panalangin ay magsisimula muli nito.\n\nEsc ang balik sa aklatan. F1 o ? ang tulong. q ang pag-save at paglabas. Naka-save ang progreso sa bawat pagbabago.\n\nSa makitid na terminal, Tab ang paglipat sa aklatan at pagbasa. Hindi mawawala ang iyong puwesto kapag binago ang laki.",
      "Tab passe de la bibliothèque à la zone de lecture. Espace ou Entrée avance ; Retour arrière recule. Les réglages permettent de désactiver séparément les flèches et la barre d’espace.\n\nDans la bibliothèque, Haut/Bas choisit un élément ; Entrée l’ouvre.\n\nPendant la lecture, Gauche/Droite passe à la prière précédente/suivante. Haut/Bas fait défiler le texte. Page précédente/suivante fait défiler une page. Début/Fin va au début/à la fin du texte.\n\nÀ la dernière prière, Entrée marque la prière comme terminée. Retour arrière revient à la prière.\n\nLes réglages permettent de changer la langue de l’app, la langue de prière, les mystères, la forme ou le jour. Gauche/Droite change la valeur. Modifier un réglage de prière la recommence.\n\nÉchap revient à la bibliothèque. F1 ou ? ouvre l’aide. q enregistre la progression et quitte. La progression est enregistrée après chaque modification.\n\nDans un terminal étroit, Tab alterne entre bibliothèque et lecture. Vous pouvez redimensionner sans perdre votre place.",
      "Tab sposta il focus tra la raccolta e l’area di lettura. Spazio o Invio avanza; Backspace torna indietro. Nelle impostazioni puoi disattivare separatamente frecce e barra spaziatrice.\n\nNella raccolta, Su/Giù seleziona una voce; Invio la apre.\n\nDurante la lettura, Sinistra/Destra passa alla preghiera precedente/successiva. Su/Giù scorre il testo. Pagina su/giù scorre una pagina. Inizio/Fine va all’inizio/alla fine del testo.\n\nAll’ultima preghiera, Invio segna il completamento. Backspace torna alla preghiera.\n\nNelle impostazioni puoi cambiare lingua dell’app, lingua di preghiera, misteri, forma o giorno. Sinistra/Destra cambia il valore. Cambiare un’impostazione di preghiera la ricomincia.\n\nEsc torna alla raccolta. F1 o ? apre l’aiuto. q salva i progressi ed esce. I progressi vengono salvati dopo ogni modifica.\n\nNei terminali stretti, Tab alterna raccolta e lettura. Il ridimensionamento conserva la tua posizione.",
      "Tab перемикає фокус між бібліотекою та областю читання. Пробіл або Enter — уперед, Backspace — назад. Стрілки й пробіл можна вимкнути окремо в налаштуваннях.\n\nУ бібліотеці Вгору/вниз вибирає пункт; Enter відкриває його.\n\nПід час читання Ліворуч/праворуч переходить до попередньої/наступної молитви. Вгору/вниз прокручує текст. Page Up/Page Down прокручує сторінку. Home/End переходить на початок/кінець тексту.\n\nНа останній молитві Enter позначає завершення. Backspace повертає до молитви.\n\nУ налаштуваннях можна змінити мову застосунку, мову молитви, таємниці, варіант або день. Ліворуч/праворуч змінює значення. Зміна налаштування молитви починає її знову.\n\nEsc повертає до бібліотеки. F1 або ? відкриває довідку. q зберігає поступ і виходить. Поступ зберігається після кожної зміни.\n\nУ вузькому вікні Tab перемикає бібліотеку й читання. Зміна розміру зберігає ваше місце."
    },
    {"RTL: this build shows logical text order; correct Hebrew/Arabic needs FriBidi.", "RTL: גרסה זו מציגה סדר תווים לוגי; עברית וערבית תקינות דורשות FriBidi.", "RTL: يعرض هذا الإصدار الترتيب المنطقي؛ العرض الصحيح للعربية والعبرية يحتاج FriBidi.", "RTL: здесь логический порядок текста; для иврита и арабского нужен FriBidi.", "RTL: lohikal ang ayos dito; kailangan ng FriBidi para sa Hebreo/Arabe.", "RTL : ordre logique ; l’hébreu et l’arabe nécessitent FriBidi.", "RTL: ordine logico; per ebraico e arabo serve FriBidi.", "RTL: логічний порядок тексту; для івриту й арабської потрібен FriBidi."},
    {"Source language", "שפת המקור", "لغة المصدر", "Язык источника", "Wika ng pinagmulan", "Langue source", "Lingua originale", "Мова джерела"},
    {"Could not save progress. Check the state file location.", "לא ניתן לשמור התקדמות. בדקו את מיקום קובץ המצב.", "تعذر حفظ التقدم. تحقق من موقع ملف الحالة.", "Не удалось сохранить прогресс. Проверьте путь к файлу состояния.", "Hindi ma-save ang progreso. Suriin ang lokasyon ng state file.", "Impossible d’enregistrer la progression. Vérifiez l’emplacement du fichier d’état.", "Impossibile salvare i progressi. Controlla il percorso del file di stato.", "Не вдалося зберегти поступ. Перевірте шлях до файлу стану."},
    {"Could not open this prayer", "לא ניתן לפתוח תפילה זו", "تعذر فتح هذه الصلاة", "Не удалось открыть молитву", "Hindi mabuksan ang panalangin", "Impossible d’ouvrir cette prière", "Impossibile aprire questa preghiera", "Не вдалося відкрити молитву"},
    {"No prayers were found.", "לא נמצאו תפילות.", "لم يتم العثور على صلوات.", "Молитвы не найдены.", "Walang nahanap na panalangin.", "Aucune prière trouvée.", "Nessuna preghiera trovata.", "Молитов не знайдено."},
    {"Enlarge the terminal (at least 24 x 8). q: quit", "הגדילו את המסוף (לפחות 24 x 8). q: יציאה", "كبّر الطرفية (24 x 8 على الأقل). q: خروج", "Увеличьте окно (минимум 24 x 8). q: выход", "Palakihin ang terminal (24 x 8 man lang). q: labas", "Agrandissez le terminal (24 x 8 minimum). q : quitter", "Ingrandisci il terminale (almeno 24 x 8). q: esci", "Збільште вікно (щонайменше 24 x 8). q: вихід"},
    {"Joyful", "השמחה", "الفرحة", "Радостные", "Tuwa", "Joyeux", "Gaudiosi", "Радісні"},
    {"Sorrowful", "המוכאבות", "الحزينة", "Скорбные", "Hapis", "Douloureux", "Dolorosi", "Скорботні"},
    {"Glorious", "הכבוד", "المجيدة", "Славные", "Luwalhati", "Glorieux", "Gloriosi", "Славні"},
    {"Luminous", "האור", "النورانية", "Светлые", "Liwanag", "Lumineux", "Luminosi", "Світлі"},
    {"Backspace: return to prayer. Select a prayer in the library to start again.", "Backspace: חזרה לתפילה. בחרו תפילה בספרייה להתחלה מחדש.", "Backspace: العودة للصلاة. اختر صلاة في المكتبة للبدء مجددًا.", "Backspace: вернуться к молитве. Выберите молитву в библиотеке, чтобы начать заново.", "Backspace: bumalik. Pumili sa aklatan upang magsimulang muli.", "Retour arrière : revenir à la prière. Choisissez une prière pour recommencer.", "Backspace: torna alla preghiera. Seleziona una preghiera per ricominciare.", "Backspace: повернутися до молитви. Виберіть молитву в бібліотеці, щоб почати знову."},
    {"Left/Right changes a value. Prayer changes start at the first step.", "שמאל/ימין משנה ערך. שינוי תפילה מתחיל בשלב הראשון.", "يسار/يمين يغيّر القيمة. تغيير الصلاة يبدأ من الخطوة الأولى.", "Влево/вправо меняет значение. Изменение молитвы начинает её с первого шага.", "Kaliwa/Kanan ang pagbabago. Magsisimula ang panalangin sa unang hakbang.", "Gauche/Droite change une valeur. La prière recommence au premier pas.", "Sinistra/Destra cambia un valore. La preghiera ricomincia dal primo passo.", "Ліворуч/праворуч змінює значення. Молитва починається з першого кроку."},
    {"Progress saved", "ההתקדמות נשמרה", "تم حفظ التقدم", "Прогресс сохранён", "Naka-save ang progreso", "Progression enregistrée", "Progressi salvati", "Поступ збережено"},
    {"No text is supplied for this step.", "לא סופק טקסט לשלב זה.", "لا يتوفر نص لهذه الخطوة.", "Текст для этого шага не указан.", "Walang teksto para sa hakbang na ito.", "Aucun texte fourni pour cette étape.", "Nessun testo disponibile per questo passo.", "Текст для цього кроку не вказано."},
    {"Includes source text in more than one language", "כולל טקסט מקור ביותר משפה אחת", "يتضمن نصًا مصدريًا بأكثر من لغة", "Содержит исходный текст на нескольких языках", "May tekstong mula sa higit sa isang wika", "Contient des textes sources en plusieurs langues", "Contiene testi originali in più lingue", "Містить вихідний текст кількома мовами"},
    {"Includes text in a fallback language", "כולל טקסט בשפה חלופית", "يتضمن نصًا بلغة بديلة", "Содержит текст на резервном языке", "May teksto sa alternatibong wika", "Contient du texte dans une langue de repli", "Contiene testo in una lingua alternativa", "Містить текст резервною мовою"},
    {"Use arrow keys to navigate", "ניווט באמצעות מקשי החצים", "التنقل بمفاتيح الأسهم", "Навигация клавишами со стрелками", "Gamitin ang mga arrow key sa pag-navigate", "Naviguer avec les touches fléchées", "Naviga con i tasti freccia", "Навігація клавішами зі стрілками"},
    {"Press Space to advance", "התקדמות באמצעות מקש הרווח", "التقدم بمفتاح المسافة", "Переход вперёд клавишей пробела", "Pindutin ang Space para magpatuloy", "Avancer avec la barre d’espace", "Avanza con la barra spaziatrice", "Перехід уперед клавішею пробілу"},
    {"On", "פעיל", "مفعّل", "Вкл.", "Naka-on", "Activé", "Attivo", "Увімкнено"},
    {"Off", "כבוי", "معطّل", "Выкл.", "Naka-off", "Désactivé", "Disattivo", "Вимкнено"}
};

#endif
