// Regenerates lib/embedded-assets.generated.ts from migrations/*.sql and seed/*.
// Runs automatically via package.json pre-hooks (prebuild, predb:migrate, predb:seed),
// so the generated module can never drift from the source files. This exists because
// outputFileTracingIncludes does not ship the files into the function under this
// monorepo's Root Directory setup — embedding sidesteps the tracer entirely.

import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";

const root = new URL("..", import.meta.url).pathname;

const migrationFiles = (await readdir(join(root, "migrations"))).filter((f) => f.endsWith(".sql")).sort();
const migrations = await Promise.all(
  migrationFiles.map(async (id) => ({
    id,
    sql: await readFile(join(root, "migrations", id), "utf-8"),
  }))
);

const seedFiles = (await readdir(join(root, "seed"))).filter((f) => f.endsWith(".prosaryprayer")).sort();
const seeds = await Promise.all(
  seedFiles.map(async (name) => ({
    name,
    base64: (await readFile(join(root, "seed", name))).toString("base64"),
  }))
);

const out = `// GENERATED by scripts/embed-assets.ts — do not edit; edit migrations/*.sql and seed/* instead.

export const MIGRATIONS: { id: string; sql: string }[] = ${JSON.stringify(migrations, null, 2)};

export const SEED_BUNDLES: { name: string; base64: string }[] = ${JSON.stringify(seeds, null, 2)};
`;
await writeFile(join(root, "lib", "embedded-assets.generated.ts"), out);
console.log(`embedded ${migrations.length} migration(s), ${seeds.length} seed bundle(s)`);
