#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# ///
"""Pinned source-specific reference reviews for Synodal, Crampon and Martini.

No Scripture wording is stored here. Profiles apply only after the registry has
verified the exact assembled source-pin digest. Empty override targets denote
source additions without an ordinary STEP Standard verse; they are unavailable.
Reviewed inventory exceptions are explicit source boundaries, not an instruction
to treat every last imported row as a complete chapter.
"""
from collections import defaultdict
from reading_versification import Versification


def _crampon_psalms():
    """Complete Hebrew-to-Standard Psalm relations, including numbered titles."""
    english = Versification().tables["eng"]  # verifies all pinned SIL tables
    result = defaultdict(set)
    for (book, chapter), maximum in english.maxima.items():
        if book != "PSA":
            continue
        for verse in range(1, maximum + 1):
            standard = (book, chapter, verse)
            for source in english.explicit.get(standard, {standard}):
                result[source].add(standard)
    for standard, sources in english.explicit.items():
        if standard[0] == "PSA" and standard[2] == 0:
            for source in sources:
                result[source].add(standard)
    # The source merges these printed superscriptions with body verse one.
    # Psalm 96 begins with an imperative, not a superscription, and is excluded.
    merged_titles = {11,14,15,17,23,24,25,26,27,28,29,32,35,37,66,72,73,74,
                     78,79,82,86,87,90,98,100,103,109,110,*range(120,135),
                     138,139,141,143,144,145}
    for chapter in merged_titles:
        result[("PSA", chapter, 1)].add(("PSA", chapter, 0))
    return {source: tuple(sorted(targets)) for source, targets in result.items()
            if source[1] not in {50,101}}


PROFILES = {'crampon-1923': {'blocked_chapters': {('1CH', 11),
                                       ('1CH', 12),
                                       ('1CO', 16),
                                       ('3JN', 1),
                                       ('ACT', 10),
                                       ('ACT', 14),
                                       ('ACT', 19),
                                       ('DAN', 14),
                                       ('DEU', 5),
                                       ('ECC', 7),
                                       ('HEB', 13),
                                       ('ISA', 8),
                                       ('ISA', 9),
                                       ('ISA', 38),
                                       ('JDG', 21),
                                       ('JDT', 1),
                                       ('JDT', 2),
                                       ('JDT', 7),
                                       ('JDT', 8),
                                       ('JDT', 10),
                                       ('JDT', 11),
                                       ('JDT', 14),
                                       ('JHN', 11),
                                       ('JOB', 25),
                                       ('JOB', 27),
                                       ('JOS', 21),
                                       ('MAT', 17),
                                       ('MRK', 4),
                                       ('MRK', 9),
                                       ('NUM', 26),
                                       ('PSA', 50),
                                       ('PSA', 101),
                                       ('SIR', 3),
                                       ('SIR', 5),
                                       ('SIR', 10),
                                       ('SIR', 11),
                                       ('SIR', 13),
                                       ('SIR', 16),
                                       ('SIR', 17),
                                       ('SIR', 18),
                                       ('SIR', 19),
                                       ('SIR', 20),
                                       ('SIR', 22),
                                       ('SIR', 23),
                                       ('SIR', 24),
                                       ('SIR', 25),
                                       ('SIR', 26),
                                       ('SIR', 32),
                                       ('SIR', 33),
                                       ('SIR', 34),
                                       ('SIR', 36),
                                       ('SIR', 41),
                                       ('SIR', 43),
                                       ('SIR', 48),
                                       ('SNG', 4),
                                       ('TOB', 10),
                                       ('WIS', 9),
                                       ('ZEC', 4)},
                  'local_rule_lines': {6093,
                                       20268,
                                       20269,
                                       20270,
                                       20271,
                                       20272,
                                       20273,
                                       20274,
                                       20275,
                                       20276,
                                       20277,
                                       20278,
                                       20279,
                                       20280,
                                       20281,
                                       20282,
                                       20283,
                                       20284,
                                       20285,
                                       20286,
                                       20287,
                                       20288,
                                       20289,
                                       20290,
                                       20291,
                                       20292,
                                       20293,
                                       20294,
                                       20295,
                                       20297,
                                       20298,
                                       20299,
                                       20300,
                                       20301,
                                       20302,
                                       20303,
                                       20304,
                                       20305,
                                       20306,
                                       20307,
                                       20308,
                                       20309,
                                       20310,
                                       20311,
                                       20312,
                                       20313,
                                       20314,
                                       20315,
                                       20316,
                                       20317,
                                       20318,
                                       20319,
                                       20320,
                                       20321,
                                       20322,
                                       20323,
                                       20324,
                                       20325,
                                       20326,
                                       20327,
                                       20328,
                                       20329,
                                       20330,
                                       20331,
                                       20332,
                                       20333,
                                       20334,
                                       20335,
                                       20336,
                                       20337,
                                       20338,
                                       20339,
                                       20340,
                                       20341,
                                       20342,
                                       20343,
                                       20344,
                                       20345,
                                       20346,
                                       20574,
                                       20575,
                                       20576,
                                       20577,
                                       20578,
                                       20579,
                                       20580,
                                       20581,
                                       20582,
                                       20583,
                                       20584,
                                       20585,
                                       20586,
                                       20587,
                                       20588,
                                       20589,
                                       20590,
                                       20591,
                                       20592,
                                       20593,
                                       20594,
                                       20595,
                                       20596,
                                       20597,
                                       20598,
                                       20599,
                                       20600,
                                       20601,
                                       20602,
                                       20603,
                                       20604,
                                       20605,
                                       20606,
                                       20607,
                                       21423,
                                       21424,
                                       21425,
                                       21426,
                                       21698,
                                       21699,
                                       21700,
                                       21701,
                                       21702,
                                       21703,
                                       21704,
                                       21705,
                                       21706,
                                       21707,
                                       21708,
                                       21709,
                                       21710,
                                       21711,
                                       21712,
                                       21713,
                                       21714,
                                       21715,
                                       21716,
                                       21717,
                                       21718,
                                       21719,
                                       21720,
                                       21721,
                                       25120,
                                       25148,
                                       26111,
                                       26112,
                                       26113,
                                       26114,
                                       26115,
                                       26116,
                                       26117,
                                       26118,
                                       26119,
                                       26120,
                                       26121,
                                       26122,
                                       26123,
                                       26124,
                                       26131,
                                       26132,
                                       26296,
                                       26297,
                                       26299,
                                       26300,
                                       26304,
                                       27455,
                                       27456,
                                       27471},
                  'notes': ('Pinned FreCrampon JSON contains 73 books, 1,334 chapters; 124 empty entries across 58 '
                            'malformed chapters remain excluded in full.',
                            'OT primarily follows Hebrew inventory, NT English/Greek; local Latin '
                            'integrated Daniel and Baruch, Tobit/Maccabees boundaries retain published STEP '
                            'relations. Philippians 1:16-17 swaps.',
                            'All 148 nonmalformed Psalm chapter inventories match SIL Original exactly. Their '
                            'complete correspondence uses SIL numeric title/split relations; reviewed '
                            'merged-title slots remain indivisible.',
                            'Safe deuterocanonical chapter endpoints were compared with the official complete '
                            'NABRE inventory; different Tobit 5/6/11 and 1 Maccabees 12 boundaries are covered by '
                            'STEP. Esther 10-16 and Daniel 3/13 retain their complete integrated addition '
                            'inventories.',
                            'Daniel 13:1-64 is Susanna 1:1-64; standalone SUS is absent in this source. Explicit '
                            'adapter avoids treating absent-book predicates as evidence of truncation.',
                            'Sources: '
                            'https://github.com/scrollmapper/bible_databases/blob/master/formats/json/FreCrampon.json '
                            '; pinned STEP/SIL; https://bible.usccb.org/bible .'),
                  'overrides': {('DAN', 13, 1): (('SUS', 1, 1),),
                                ('DAN', 13, 2): (('SUS', 1, 2),),
                                ('DAN', 13, 3): (('SUS', 1, 3),),
                                ('DAN', 13, 4): (('SUS', 1, 4),),
                                ('DAN', 13, 5): (('SUS', 1, 5),),
                                ('DAN', 13, 6): (('SUS', 1, 6),),
                                ('DAN', 13, 7): (('SUS', 1, 7),),
                                ('DAN', 13, 8): (('SUS', 1, 8),),
                                ('DAN', 13, 9): (('SUS', 1, 9),),
                                ('DAN', 13, 10): (('SUS', 1, 10),),
                                ('DAN', 13, 11): (('SUS', 1, 11),),
                                ('DAN', 13, 12): (('SUS', 1, 12),),
                                ('DAN', 13, 13): (('SUS', 1, 13),),
                                ('DAN', 13, 14): (('SUS', 1, 14),),
                                ('DAN', 13, 15): (('SUS', 1, 15),),
                                ('DAN', 13, 16): (('SUS', 1, 16),),
                                ('DAN', 13, 17): (('SUS', 1, 17),),
                                ('DAN', 13, 18): (('SUS', 1, 18),),
                                ('DAN', 13, 19): (('SUS', 1, 19),),
                                ('DAN', 13, 20): (('SUS', 1, 20),),
                                ('DAN', 13, 21): (('SUS', 1, 21),),
                                ('DAN', 13, 22): (('SUS', 1, 22),),
                                ('DAN', 13, 23): (('SUS', 1, 23),),
                                ('DAN', 13, 24): (('SUS', 1, 24),),
                                ('DAN', 13, 25): (('SUS', 1, 25),),
                                ('DAN', 13, 26): (('SUS', 1, 26),),
                                ('DAN', 13, 27): (('SUS', 1, 27),),
                                ('DAN', 13, 28): (('SUS', 1, 28),),
                                ('DAN', 13, 29): (('SUS', 1, 29),),
                                ('DAN', 13, 30): (('SUS', 1, 30),),
                                ('DAN', 13, 31): (('SUS', 1, 31),),
                                ('DAN', 13, 32): (('SUS', 1, 32),),
                                ('DAN', 13, 33): (('SUS', 1, 33),),
                                ('DAN', 13, 34): (('SUS', 1, 34),),
                                ('DAN', 13, 35): (('SUS', 1, 35),),
                                ('DAN', 13, 36): (('SUS', 1, 36),),
                                ('DAN', 13, 37): (('SUS', 1, 37),),
                                ('DAN', 13, 38): (('SUS', 1, 38),),
                                ('DAN', 13, 39): (('SUS', 1, 39),),
                                ('DAN', 13, 40): (('SUS', 1, 40),),
                                ('DAN', 13, 41): (('SUS', 1, 41),),
                                ('DAN', 13, 42): (('SUS', 1, 42),),
                                ('DAN', 13, 43): (('SUS', 1, 43),),
                                ('DAN', 13, 44): (('SUS', 1, 44),),
                                ('DAN', 13, 45): (('SUS', 1, 45),),
                                ('DAN', 13, 46): (('SUS', 1, 46),),
                                ('DAN', 13, 47): (('SUS', 1, 47),),
                                ('DAN', 13, 48): (('SUS', 1, 48),),
                                ('DAN', 13, 49): (('SUS', 1, 49),),
                                ('DAN', 13, 50): (('SUS', 1, 50),),
                                ('DAN', 13, 51): (('SUS', 1, 51),),
                                ('DAN', 13, 52): (('SUS', 1, 52),),
                                ('DAN', 13, 53): (('SUS', 1, 53),),
                                ('DAN', 13, 54): (('SUS', 1, 54),),
                                ('DAN', 13, 55): (('SUS', 1, 55),),
                                ('DAN', 13, 56): (('SUS', 1, 56),),
                                ('DAN', 13, 57): (('SUS', 1, 57),),
                                ('DAN', 13, 58): (('SUS', 1, 58),),
                                ('DAN', 13, 59): (('SUS', 1, 59),),
                                ('DAN', 13, 60): (('SUS', 1, 60),),
                                ('DAN', 13, 61): (('SUS', 1, 61),),
                                ('DAN', 13, 62): (('SUS', 1, 62),),
                                ('DAN', 13, 63): (('SUS', 1, 63),),
                                ('DAN', 13, 64): (('SUS', 1, 64),)},
                  'reviewed_inventory_exceptions': {('1MA', 1),
                                                    ('1MA', 2),
                                                    ('1MA', 3),
                                                    ('1MA', 4),
                                                    ('1MA', 5),
                                                    ('1MA', 6),
                                                    ('1MA', 7),
                                                    ('1MA', 8),
                                                    ('1MA', 9),
                                                    ('1MA', 10),
                                                    ('1MA', 11),
                                                    ('1MA', 12),
                                                    ('1MA', 13),
                                                    ('1MA', 14),
                                                    ('1MA', 15),
                                                    ('1MA', 16),
                                                    ('2CO', 13),
                                                    ('2MA', 1),
                                                    ('2MA', 2),
                                                    ('2MA', 3),
                                                    ('2MA', 4),
                                                    ('2MA', 5),
                                                    ('2MA', 6),
                                                    ('2MA', 7),
                                                    ('2MA', 8),
                                                    ('2MA', 9),
                                                    ('2MA', 10),
                                                    ('2MA', 11),
                                                    ('2MA', 12),
                                                    ('2MA', 13),
                                                    ('2MA', 14),
                                                    ('2MA', 15),
                                                    ('BAR', 1),
                                                    ('BAR', 2),
                                                    ('BAR', 3),
                                                    ('BAR', 4),
                                                    ('BAR', 5),
                                                    ('BAR', 6),
                                                    ('DAN', 3),
                                                    ('DAN', 13),
                                                    ('EST', 10),
                                                    ('EST', 11),
                                                    ('EST', 12),
                                                    ('EST', 13),
                                                    ('EST', 14),
                                                    ('EST', 15),
                                                    ('EST', 16),
                                                    ('JDG', 5),
                                                    ('JDT', 3),
                                                    ('JDT', 4),
                                                    ('JDT', 5),
                                                    ('JDT', 6),
                                                    ('JDT', 9),
                                                    ('JDT', 12),
                                                    ('JDT', 13),
                                                    ('JDT', 15),
                                                    ('JDT', 16),
                                                    ('NEH', 7),
                                                    ('SIR', 1),
                                                    ('SIR', 2),
                                                    ('SIR', 4),
                                                    ('SIR', 6),
                                                    ('SIR', 7),
                                                    ('SIR', 8),
                                                    ('SIR', 9),
                                                    ('SIR', 12),
                                                    ('SIR', 14),
                                                    ('SIR', 15),
                                                    ('SIR', 21),
                                                    ('SIR', 27),
                                                    ('SIR', 28),
                                                    ('SIR', 29),
                                                    ('SIR', 30),
                                                    ('SIR', 31),
                                                    ('SIR', 35),
                                                    ('SIR', 37),
                                                    ('SIR', 38),
                                                    ('SIR', 39),
                                                    ('SIR', 40),
                                                    ('SIR', 42),
                                                    ('SIR', 44),
                                                    ('SIR', 45),
                                                    ('SIR', 46),
                                                    ('SIR', 47),
                                                    ('SIR', 49),
                                                    ('SIR', 50),
                                                    ('SIR', 51),
                                                    ('TOB', 1),
                                                    ('TOB', 2),
                                                    ('TOB', 3),
                                                    ('TOB', 4),
                                                    ('TOB', 5),
                                                    ('TOB', 6),
                                                    ('TOB', 7),
                                                    ('TOB', 8),
                                                    ('TOB', 9),
                                                    ('TOB', 11),
                                                    ('TOB', 12),
                                                    ('TOB', 13),
                                                    ('TOB', 14),
                                                    ('WIS', 1),
                                                    ('WIS', 2),
                                                    ('WIS', 3),
                                                    ('WIS', 4),
                                                    ('WIS', 5),
                                                    ('WIS', 6),
                                                    ('WIS', 7),
                                                    ('WIS', 8),
                                                    ('WIS', 10),
                                                    ('WIS', 11),
                                                    ('WIS', 12),
                                                    ('WIS', 13),
                                                    ('WIS', 14),
                                                    ('WIS', 15),
                                                    ('WIS', 16),
                                                    ('WIS', 17),
                                                    ('WIS', 18),
                                                    ('WIS', 19)},
                  'source_pin_digest': '78da62bd4314baaa0399c6a5b622150665e8574decbfe14e437f97d75bc7f76c',
                  'source_types': {'EngTitleMerged', 'EngTitleSeparate', 'Eng-KJV', 'Hebrew', 'Eng-NRSV', 'NRSV'}},
 'martini': {'blocked_chapters': {('1TH', 4), ('1PE', 5), ('JHN', 11)},
             'local_rule_lines': {5776,
                                  5777,
                                  5778,
                                  5779,
                                  5780,
                                  5781,
                                  5782,
                                  5783,
                                  5784,
                                  5785,
                                  5786,
                                  5787,
                                  5788,
                                  5789,
                                  5790,
                                  5791,
                                  5792,
                                  5793,
                                  5794,
                                  5858,
                                  5859,
                                  5860,
                                  5861,
                                  5862,
                                  5863,
                                  5864,
                                  5865,
                                  5866,
                                  5867,
                                  5868,
                                  5869,
                                  5870,
                                  5871,
                                  5872,
                                  5873,
                                  5874,
                                  5875,
                                  5876,
                                  5877,
                                  5878,
                                  5879,
                                  5880,
                                  5881,
                                  5882,
                                  5883,
                                  5938,
                                  5939,
                                  5940,
                                  5941,
                                  5942,
                                  5943,
                                  5944,
                                  5945,
                                  5946,
                                  5947,
                                  5948,
                                  5949,
                                  5950,
                                  5951,
                                  5952,
                                  5953,
                                  5954,
                                  5955,
                                  5956,
                                  5957,
                                  5958,
                                  5959,
                                  5960,
                                  5961,
                                  5962,
                                  5963,
                                  5964,
                                  5965,
                                  5966,
                                  27449,
                                  27450,
                                  27451,
                                  27455,
                                  27456},
             'notes': ('Pinned Parola Viva payloads contain 447 chapters: Pentateuch and NT only. No Psalms or '
                       'deuterocanonical text is imported.',
                       'Predominantly Latin divisions, with locally reviewed Hebrew chapter moves in Deuteronomy '
                       'and Greek 2 Corinthians 13/Philippians 1 divisions. Philippians 1:16-17 is swapped against '
                       'Standard.',
                       'Genesis 5:31 merges Standard 31-32; 2 Corinthians 1:23 merges 23-24; 2 Thessalonians 2:10 '
                       'merges 10-11 and 11-16 follow one verse later.',
                       '1 Peter 5 has only 11-14; 1 Thessalonians 4 omits 18; John 11 omits 57. The last two missing verses '
                       'are not carried into their next chapters. Exclude all three chapters before predicates.',
                       'Sources: https://parolaviva.art/api/v1/bibbia/ ; source lock pins every imported chapter. '
                       'https://ebible.org/eng-kjv/2TH02.htm and https://ebible.org/eng-kjv/2CO01.htm identify complete Standard units.'),
             'overrides': {('2CO', 1, 23): (('2CO', 1, 23), ('2CO', 1, 24)),
                           ('2TH', 2, 10): (('2TH', 2, 10), ('2TH', 2, 11)),
                           ('2TH', 2, 11): (('2TH', 2, 12),),
                           ('2TH', 2, 12): (('2TH', 2, 13),),
                           ('2TH', 2, 13): (('2TH', 2, 14),),
                           ('2TH', 2, 14): (('2TH', 2, 15),),
                           ('2TH', 2, 15): (('2TH', 2, 16),),
                           ('2TH', 2, 16): (('2TH', 2, 17),)},
             'reviewed_inventory_exceptions': {('2CO', 1),
                                               ('2TH', 2),
                                               ('3JN', 1),
                                               ('DEU', 12),
                                               ('DEU', 13),
                                               ('DEU', 22),
                                               ('DEU', 23),
                                               ('DEU', 28),
                                               ('DEU', 29),
                                               ('GEN', 5)},
             'source_pin_digest': '8dac39be02b7103aa6f70d2c516fd6899bc6ba2d704233950b18482a31162b0e',
             'source_types': {'3Latin', 'Latin=', 'LatinUndivided', 'Latin2', 'Latin', 'Italian'}},
 'synodal-1876': {'blocked_chapters': set(),
                  'local_rule_lines': {6086,
                                       6087,
                                       6088,
                                       6144,
                                       10156,
                                       10157,
                                       10158,
                                       10159,
                                       10160,
                                       10161,
                                       10162,
                                       10163,
                                       10164,
                                       10165,
                                       10166,
                                       10167,
                                       10168,
                                       10169,
                                       10170,
                                       10171,
                                       10172,
                                       10173,
                                       10174,
                                       10175,
                                       10176,
                                       10177,
                                       10178,
                                       10179,
                                       10180,
                                       10181,
                                       10182,
                                       10183,
                                       10184,
                                       10185,
                                       10186,
                                       10187,
                                       10188,
                                       10189,
                                       10190,
                                       10191,
                                       10192,
                                       10193,
                                       10194,
                                       10195,
                                       10196,
                                       10197,
                                       10198,
                                       10199,
                                       10200,
                                       10201,
                                       10202,
                                       10203,
                                       10204,
                                       10205,
                                       10206,
                                       10207,
                                       10208,
                                       10209,
                                       10210,
                                       10211,
                                       10212,
                                       10213,
                                       10682,
                                       10684,
                                       10685,
                                       10686,
                                       10687,
                                       10689,
                                       10690,
                                       17731,
                                       17925,
                                       17926,
                                       18101,
                                       18103,
                                       18104,
                                       18105,
                                       18106,
                                       18107,
                                       18108,
                                       18109,
                                       18110,
                                       18111,
                                       18112,
                                       18113,
                                       18114,
                                       18115,
                                       18116,
                                       18117,
                                       27434,
                                       27435,
                                       27436},
                  'notes': ('Pinned eBible russyn corpus: 66 books, 1,189 chapters. Mixed '
                            'English, Hebrew, Greek/Slavonic local traditions are selected by published STEP '
                            'predicates.',
                            'Local rows preserve Job 39-41, Song 1, Romans 14:24-26 and 1 Samuel 20:43. Psalms 12, 86, 89 '
                            'have source-inspected title/body divisions; Psalm 141:1 merges title/body.',
                            'Psalm 114 has nine complete verses; Proverbs 18 has 24; Daniel 3 omits the Greek additions '
                            'and carries Standard 4:1-3 in 3:31-33. These three actual inventories differ from '
                            'generic SIL Russian Orthodox.',
                            'Joshua 24:34-36 and Proverbs 4:28-29 are supplementary clauses with no ordinary '
                            'Standard verse counterpart; empty override intentionally withholds them.',
                            'Sources: https://ebible.org/russyn/ ; pinned STEP TVTMS and SIL metadata in '
                            'versification/ .'),
                  'overrides': {('JOS', 24, 34): (),
                                ('JOS', 24, 35): (),
                                ('JOS', 24, 36): (),
                                ('PRO', 4, 28): (),
                                ('PRO', 4, 29): (),
                                ('PSA', 12, 1): (('PSA', 13, 0),),
                                ('PSA', 12, 2): (('PSA', 13, 1),),
                                ('PSA', 12, 3): (('PSA', 13, 2),),
                                ('PSA', 12, 4): (('PSA', 13, 3),),
                                ('PSA', 12, 5): (('PSA', 13, 4),),
                                ('PSA', 12, 6): (('PSA', 13, 5), ('PSA', 13, 6)),
                                ('PSA', 86, 1): (('PSA', 87, 0),),
                                ('PSA', 86, 2): (('PSA', 87, 1), ('PSA', 87, 2)),
                                ('PSA', 89, 1): (('PSA', 90, 0),),
                                ('PSA', 89, 2): (('PSA', 90, 1),),
                                ('PSA', 89, 3): (('PSA', 90, 2),),
                                ('PSA', 89, 4): (('PSA', 90, 3),),
                                ('PSA', 89, 5): (('PSA', 90, 4),),
                                ('PSA', 89, 6): (('PSA', 90, 5), ('PSA', 90, 6)),
                                ('PSA', 141, 1): (('PSA', 142, 0), ('PSA', 142, 1))},
                  'reviewed_inventory_exceptions': {('DAN', 3), ('PSA', 114), ('PRO', 18)},
                  'source_pin_digest': '13bed0e3346ae97612b7a64af4c42bb4af3382b37eed2a276b7a4c8d5e33142e',
                  'source_types': {'Eng-KJV',
                                   'Greek',
                                   'GreekUndivided',
                                   'GrkTitleMerged',
                                   'GrkTitleSeparate',
                                   'GrkTitleSeparate2',
                                   'Hebrew',
                                   'Slavonic'}}}

PROFILES["crampon-1923"]["overrides"].update(_crampon_psalms())
