#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# ///
"""Reference-only profile for the exact eBible Greek Brenton VPL import.

The pin and corpus digest bind the actual 908 complete integer-label chapters.
The excluded source layouts are deliberate: their omissions cannot be used as
proof of different verse boundaries by STEP predicates. Greek/Brenton variant
rules are conditional on the pinned source's labels and word counts; unresolved
conditions/conflicting rules remain blocked. GreekIntegrated and NETS-specific
rules are not selected. No Latin family or guessed blanket Psalm offset is used.
Sources: https://ebible.org/Scriptures/details.php?id=grcbrent and the pinned
STEP TVTMS provenance at versification/step/sources.json. Brenton variants are
explicitly distinguished in TVTMS's Genesis36–37, Exodus35, Deuteronomy22–23,
Joshua8–9, Job39–41 and Psalm title sections.
"""
from reading_step_mapping import Unavailable
from reading_standard_bridge import standard_chapter_max
from reading_versification import SUPPORTED_BOOKS, chapter_verse_count


def sil_english_ot_to_standard(references):
    """The supported OT body labels coincide; the NT bridge is not an identity.

    Chapter endpoint agreement is rechecked against both pinned inventories.
    Psalm title slots and additional books need their explicit source adapters.
    """
    nt = set("MAT MRK LUK JHN ACT ROM 1CO 2CO GAL EPH PHP COL 1TH 2TH 1TI 2TI TIT PHM HEB JAS 1PE 2PE 1JN 2JN 3JN JUD REV".split())
    result = list(references)
    for book, chapter, verse in result:
        maximum = standard_chapter_max(book, chapter)
        if (book not in SUPPORTED_BOOKS or book in nt or maximum is None
                or maximum != chapter_verse_count(book, chapter, "eng")
                or not 1 <= verse <= maximum):
            raise Unavailable("reference outside the reviewed Old Testament bridge")
    return result


PROFILES = {'brenton-lxx': {'blocked_chapters': {('1CH', 1),
                                      ('1CH', 16),
                                      ('1ES', 1),
                                      ('1ES', 2),
                                      ('1ES', 3),
                                      ('1ES', 4),
                                      ('1ES', 5),
                                      ('1ES', 6),
                                      ('1ES', 7),
                                      ('1ES', 8),
                                      ('1ES', 9),
                                      ('1KI', 2),
                                      ('1KI', 3),
                                      ('1KI', 5),
                                      ('1KI', 6),
                                      ('1KI', 8),
                                      ('1KI', 9),
                                      ('1KI', 10),
                                      ('1KI', 11),
                                      ('1KI', 12),
                                      ('1KI', 13),
                                      ('1KI', 14),
                                      ('1KI', 15),
                                      ('1KI', 16),
                                      ('1KI', 22),
                                      ('1SA', 13),
                                      ('1SA', 17),
                                      ('1SA', 18),
                                      ('1SA', 23),
                                      ('1SA', 30),
                                      ('2CH', 3),
                                      ('2CH', 27),
                                      ('2CH', 35),
                                      ('2CH', 36),
                                      ('2KI', 1),
                                      ('2SA', 5),
                                      ('2SA', 23),
                                      ('3MA', 1),
                                      ('3MA', 2),
                                      ('3MA', 3),
                                      ('3MA', 4),
                                      ('3MA', 5),
                                      ('3MA', 6),
                                      ('3MA', 7),
                                      ('4MA', 1),
                                      ('4MA', 2),
                                      ('4MA', 3),
                                      ('4MA', 4),
                                      ('4MA', 5),
                                      ('4MA', 6),
                                      ('4MA', 7),
                                      ('4MA', 8),
                                      ('4MA', 9),
                                      ('4MA', 10),
                                      ('4MA', 11),
                                      ('4MA', 12),
                                      ('4MA', 13),
                                      ('4MA', 14),
                                      ('4MA', 15),
                                      ('4MA', 16),
                                      ('4MA', 17),
                                      ('4MA', 18),
                                      ('BEL', 1),
                                      ('DEU', 14),
                                      ('DNG', 1),
                                      ('DNG', 2),
                                      ('DNG', 3),
                                      ('DNG', 4),
                                      ('DNG', 5),
                                      ('DNG', 6),
                                      ('DNG', 7),
                                      ('DNG', 8),
                                      ('DNG', 9),
                                      ('DNG', 10),
                                      ('DNG', 11),
                                      ('DNG', 12),
                                      ('EPJ', 1),
                                      ('ESG', 1),
                                      ('ESG', 2),
                                      ('ESG', 3),
                                      ('ESG', 4),
                                      ('ESG', 5),
                                      ('ESG', 6),
                                      ('ESG', 7),
                                      ('ESG', 8),
                                      ('ESG', 9),
                                      ('ESG', 10),
                                      ('EXO', 25),
                                      ('EXO', 28),
                                      ('EXO', 32),
                                      ('EXO', 35),
                                      ('EXO', 40),
                                      ('EZK', 1),
                                      ('EZK', 10),
                                      ('EZK', 11),
                                      ('EZK', 27),
                                      ('EZK', 32),
                                      ('EZK', 33),
                                      ('EZK', 40),
                                      ('EZR', 11),
                                      ('EZR', 12),
                                      ('EZR', 13),
                                      ('EZR', 14),
                                      ('EZR', 15),
                                      ('EZR', 16),
                                      ('EZR', 17),
                                      ('EZR', 18),
                                      ('EZR', 19),
                                      ('EZR', 20),
                                      ('EZR', 21),
                                      ('EZR', 22),
                                      ('EZR', 23),
                                      ('GEN', 31),
                                      ('GEN', 35),
                                      ('JER', 2),
                                      ('JER', 7),
                                      ('JER', 8),
                                      ('JER', 10),
                                      ('JER', 11),
                                      ('JER', 17),
                                      ('JER', 23),
                                      ('JER', 26),
                                      ('JER', 28),
                                      ('JER', 30),
                                      ('JER', 32),
                                      ('JER', 34),
                                      ('JER', 36),
                                      ('JER', 37),
                                      ('JER', 46),
                                      ('JER', 52),
                                      ('JOB', 2),
                                      ('JOB', 19),
                                      ('JOB', 23),
                                      ('JOB', 35),
                                      ('JOB', 36),
                                      ('JOB', 42),
                                      ('JOS', 6),
                                      ('JOS', 8),
                                      ('JOS', 9),
                                      ('JOS', 10),
                                      ('JOS', 15),
                                      ('JOS', 19),
                                      ('JOS', 20),
                                      ('JOS', 21),
                                      ('JOS', 24),
                                      ('LAM', 3),
                                      ('PRM', 1),
                                      ('PRO', 1),
                                      ('PRO', 3),
                                      ('PRO', 4),
                                      ('PRO', 6),
                                      ('PRO', 7),
                                      ('PRO', 8),
                                      ('PRO', 9),
                                      ('PRO', 10),
                                      ('PRO', 11),
                                      ('PRO', 12),
                                      ('PRO', 13),
                                      ('PRO', 15),
                                      ('PRO', 16),
                                      ('PRO', 17),
                                      ('PRO', 18),
                                      ('PRO', 19),
                                      ('PRO', 20),
                                      ('PRO', 21),
                                      ('PRO', 22),
                                      ('PRO', 23),
                                      ('PRO', 24),
                                      ('PRO', 25),
                                      ('PRO', 26),
                                      ('PRO', 27),
                                      ('PRO', 28),
                                      ('PRO', 31),
                                      ('PSA', 115),
                                      ('PSA', 144),
                                      ('SIR', 1),
                                      ('SIR', 3),
                                      ('SIR', 6),
                                      ('SIR', 7),
                                      ('SIR', 10),
                                      ('SIR', 11),
                                      ('SIR', 13),
                                      ('SIR', 16),
                                      ('SIR', 17),
                                      ('SIR', 18),
                                      ('SIR', 19),
                                      ('SIR', 22),
                                      ('SIR', 24),
                                      ('SIR', 25),
                                      ('SIR', 26),
                                      ('SIR', 30),
                                      ('SIR', 33),
                                      ('SUS', 1),
                                      ('TOB', 4),
                                      ('TOB', 13)},
                 'local_rule_lines': set(),
                 # The selected conditional rules leave these source references with
                 # ambiguous reverse endpoints. Do not expose a one-way identity.
                 'overrides': {('1KI', 4, 2): (), ('1KI', 4, 3): (), ('1KI', 4, 4): (),
                               ('1KI', 4, 5): (), ('EXO', 38, 11): (),
                               ('EXO', 38, 17): (), ('EXO', 39, 11): ()},
                 'reviewed_inventory_exceptions': set(),
                 'source_corpus_sha256': '70f993f3aa3fe67577167003203cf217526c3c6f1bbf6901bedf01a6c331b8c1',
                 'source_pin_digest': 'c0a60b203ea0eb359afbbe8e8c6e7245c01de9ef8890bd73d42c71e635fd4ad8',
                 'source_types': {'BrentonMerged',
                                  'Greek',
                                  'Greek2',
                                  'Greek2Undivided',
                                  'Greek3',
                                  'GreekUndivided',
                                  'GreekUndivided2',
                                  'GrkTitleMerged',
                                  'GrkTitleSeparate',
                                  'GrkTitleSeparate2'}}}
